---
- name: Install Latest k3s
  shell: curl -sfL https://get.k3s.io | K3S_URL=https://{{ hostvars[groups['master'][0]]['ansible_facts']['master_ip'] }}:6443 K3S_TOKEN={{ hostvars[groups['master'][0]]['ansible_facts']['node_token'] | quote }} sh -
