apiVersion: v1
kind: PersistentVolume
metadata:
  name: traefik-nfs-pv
  namespace: kube-system
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  nfs:
    server: k8s-master.selexin.com
    path: /mnt/usb01/traefik-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: traefik-nfs-pvc
  namespace: kube-system
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi