dashboard:
  enabled: true
  domain: traefik.rstack.selexin.dev
kubernetes:
  namespaces:
    - default
    - kube-system
  ingressEndpoint:
    useDefaultPublishedService: true
debug:
  enabled: false
rbac:
  enabled: true
ssl:
  enabled: true
acme:
  enabled: true
  staging: false
  logging: false
  delayBeforeCheck: 30
  onHostRule: true
  email: selexin@selexin.com
  challengeType: "dns-01"
  dnsProvider:
    name: cloudflare
    existingSecretName: cloudflare-api-key
  domains:
    enabled: false
  persistence:
    enabled: false
