apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: couchpotato
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: couchpotato
    spec:
      volumes:
      # Couchpotato config files (stored on USB stick on pi)
      - name: nfs-couchpotato
        nfs: 
          server: 10.1.1.9
          path: /media/NFS/couchpotato-config

      # Downloaded Files
      - name: nfs-downloads
        nfs: 
          server: 10.1.1.9
          path: /media/nzbget-k8s/completed/Movies

      # Movies Files
      - name: nfs-movies
        nfs: 
          server: 10.1.1.9
          path: /media/Movies/Movies
      - name: localtime
        hostPath:
          path: /etc/localtime
      containers:
      - name: couchpotato
        image: linuxserver/couchpotato
        # imagePullPolicy: Always
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5050
        env:
        - name: PGID
          value: "1000"
        - name: PUID
          value: "1000"
        volumeMounts:
        - name: nfs-couchpotato
          mountPath: /config
        - name: nfs-downloads
          mountPath: /downloads
        - name: nfs-movies
          mountPath: /movies
        - name: localtime
          mountPath: /etc/localtime
        resources:
          requests:
            memory: "80Mi"
            cpu: "50m"
          limits:
            memory: "100Mi"
            cpu: "200m"
      
---
apiVersion: v1
kind: Service
metadata:
  name: couchpotato
  labels:
    app: couchpotato
    kubernetes.io/name: "couchpotato"
spec:
  type: LoadBalancer
  selector:
    app: couchpotato
  ports:
  - name: couchpotato
    port: 80
    targetPort: 5050