apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: lidarr
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: lidarr
    spec:
      volumes:
      # lidarr config files (stored on USB stick on pi)
      - name: nfs-lidarr
        nfs: 
          server: 10.1.1.9
          path: /media/NFS/lidarr-config

      # Downloaded Files
      - name: nfs-downloads
        nfs: 
          server: 10.1.1.9
          path: /media/nzbget-k8s

      # Music Files
      - name: nfs-music
        nfs: 
          server: 10.1.1.9
          path: /media/Music

      containers:
      - name: lidarr
        image: linuxserver/lidarr:latest
        # imagePullPolicy: Always
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8686
        env:
        - name: PGID
          value: "1000"
        - name: PUID
          value: "1000"
        - name: TZ
          value: Australia/Sydney
        volumeMounts:
        - name: nfs-lidarr
          mountPath: /config
        - name: nfs-downloads
          mountPath: /downloads
        - name: nfs-music
          mountPath: /music
        readinessProbe:
          httpGet:
            path: /api/v1/system/status?apikey=healthcheck
            port: 8686
          initialDelaySeconds: 10
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /api/v1/system/status?apikey=healthcheck
            port: 8686
          initialDelaySeconds: 30
          periodSeconds: 5
        resources:
          requests:
            memory: "260M"
            cpu: "600m"
          limits:
            memory: "300M"
            cpu: "1000m"
---
apiVersion: v1
kind: Service
metadata:
  name: lidarr
  labels:
    app: lidarr
    kubernetes.io/name: "lidarr"
spec:
  type: LoadBalancer
  selector:
    app: lidarr
  ports:
  - name: lidarr
    port: 80
    targetPort: 8686