apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nzbget
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: nzbget
    spec:
      volumes:
      # nzbget config files (stored on USB stick on pi)
      - name: nfs-nzbget
        nfs: 
          server: 10.1.1.100
          path: /mnt/usb01/nzbget-config

      # Downloaded Files
      - name: nfs-downloads
        nfs: 
          server: 10.1.1.9
          path: /media/nzbget-k8s

      - name: localtime
        hostPath:
          path: /etc/localtime
      containers:
      - name: nzbget
        image: linuxserver/nzbget
        imagePullPolicy: Always
        ports:
        - containerPort: 6789
        env:
        - name: PGID
          value: "1000"
        - name: PUID
          value: "1000"
        volumeMounts:
        - name: nfs-nzbget
          mountPath: /config
        - name: nfs-downloads
          mountPath: /downloads
        - name: localtime
          mountPath: /etc/localtime
      
---
apiVersion: v1
kind: Service
metadata:
  name: nzbget
  labels:
    app: nzbget
    kubernetes.io/name: "nzbget"
spec:
  type: LoadBalancer
  selector:
    app: nzbget
  ports:
  - name: nzbget
    port: 80
    targetPort: 6789
---
# Internal Service for comms inside cluster
kind: Service
apiVersion: v1
metadata:
  name: nzbget-internal
spec:
  selector:
    app: nzbget
  ports:
  - protocol: TCP
    port: 6789
