apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: radarr
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: radarr
    spec:
      volumes:
      - name: nfs-radarr
        nfs: 
          server: 10.1.1.9
          path: /media/NFS/radarr-config

      # Downloaded Files
      - name: nfs-downloads
        nfs: 
          server: 10.1.1.9
          path: /media/nzbget-k8s

      # Movies
      - name: nfs-movies
        nfs: 
          server: 10.1.1.9
          path: /media/Movies/Movies
      containers:
      - name: radarr
        image: linuxserver/radarr:latest
        # imagePullPolicy: Always
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 7878
        env:
        - name: PGID
          value: "1000"
        - name: PUID
          value: "1000"
        - name: TZ
          value: Australia/Sydney
        volumeMounts:
        - name: nfs-radarr
          mountPath: /config
        - name: nfs-downloads
          mountPath: /downloads
        - name: nfs-movies
          mountPath: /movies
        readinessProbe:
          httpGet:
            path: /api/system/status?apikey=healthcheck
            port: 7878
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
        livenessProbe:
          httpGet:
            path: /api/system/status?apikey=healthcheck
            port: 7878
          initialDelaySeconds: 30
          periodSeconds: 60
          timeoutSeconds: 10
        resources:
          requests:
            memory: "200M"
            cpu: "1200m"
          limits:
            memory: "250M"
            cpu: "2000m"
---
apiVersion: v1
kind: Service
metadata:
  name: radarr
  labels:
    app: radarr
    kubernetes.io/name: "radarr"
spec:
  selector:
    app: radarr
  ports:
  - name: radarr
    port: 80
    targetPort: 7878
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: radarr-ingress
spec:
  rules:
  - host: radarr.k8s.selexin.com
    http:
      paths:
      - path: /
        backend:
          serviceName: radarr
          servicePort: 80