apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: sonarr
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: sonarr
    spec:
      volumes:
      # sonarr config files (stored on USB stick on pi)
      - name: nfs-sonarr
        nfs: 
          server: 10.1.1.100
          path: /mnt/usb01/sonarr-config

      # Downloaded Files
      - name: nfs-downloads
        nfs: 
          server: 10.1.1.9
          path: /media/nzbget-k8s

      # TV Files
      - name: nfs-tv
        nfs: 
          server: 10.1.1.9
          path: /media/TV/TV
      - name: localtime
        hostPath:
          path: /etc/localtime
      containers:
      - name: sonarr
        image: linuxserver/sonarr
        imagePullPolicy: Always
        ports:
        - containerPort: 8989
        env:
        - name: PGID
          value: "1000"
        - name: PUID
          value: "1000"
        volumeMounts:
        - name: nfs-sonarr
          mountPath: /config
        - name: nfs-downloads
          mountPath: /downloads
        - name: nfs-tv
          mountPath: /tv
        - name: localtime
          mountPath: /etc/localtime
        resources:
          requests:
            memory: "250Mi"
            cpu: "1000m"
          limits:
            memory: "350Mi"
            cpu: "1200m"
---
apiVersion: v1
kind: Service
metadata:
  name: sonarr
  labels:
    app: sonarr
    kubernetes.io/name: "sonarr"
spec:
  type: LoadBalancer
  selector:
    app: sonarr
  ports:
  - name: sonarr
    port: 80
    targetPort: 8989