apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: tautulli
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: tautulli
    spec:
      volumes:
      # tautulli config files (stored on USB stick on pi)
      - name: nfs-tautulli
        nfs: 
          server: 10.1.1.9
          path: /media/NFS/tautulli-config
      - name: localtime
        hostPath:
          path: /etc/localtime
      containers:
      - name: tautulli
        image: linuxserver/tautulli
        imagePullPolicy: Always
        # imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8181
        env:
        - name: PGID
          value: "1000"
        - name: PUID
          value: "1000"
        volumeMounts:
        - name: nfs-tautulli
          mountPath: /config
        - name: localtime
          mountPath: /etc/localtime
        resources:
          requests:
            memory: "150Mi"
            cpu: "50m"
          limits:
            memory: "180Mi"
            cpu: "100m"
      
---
apiVersion: v1
kind: Service
metadata:
  name: tautulli
  labels:
    app: tautulli
    kubernetes.io/name: "tautulli"
spec:
  type: LoadBalancer
  selector:
    app: tautulli
  ports:
  - name: tautulli
    port: 80
    targetPort: 8181